version: "3"
services:
  app:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      WAIT_HOSTS: mongo:27017
    ports:
      - 6767:6767
    command: npm run start:dev
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
